/// Tests for `decryptAndVerify`, against a real `vetkd_derive_key` reply.
///
/// These vectors are not synthesized by this repository. They come from
/// `ic-vetkeys`' own `transport_key_works_with_bls_and_ibe`
/// (`tests/utils.rs:245`), where they carry the comment "generated by internal
/// library" — the threshold implementation that runs in the replica. So passing
/// here means agreeing with what a subnet actually sends, not with this port's
/// idea of what a subnet would send.
///
/// The negative cases matter more than the positive one. `decryptAndVerify` is
/// the only thing standing between a canister and a forged vetKey, so a version
/// that returns the key without checking it would pass the happy path
/// identically.

import { test } "mo:test";
import G1 "mo:sealed-secrets-bls/G1";
import G2 "mo:sealed-secrets-bls/G2";
import Scalar "mo:sealed-secrets-bls/Scalar";
import VetKey "../src/VetKey";
import Array "mo:core/Array";
import Nat8 "mo:core/Nat8";
import Char "mo:core/Char";
import Nat32 "mo:core/Nat32";
import Text "mo:core/Text";
import Blob "mo:core/Blob";

func hexVal(c : Char) : Nat {
  let n = Nat32.toNat(Char.toNat32(c));
  if (n >= 48 and n <= 57) { n - 48 } else if (n >= 97 and n <= 102) {
    n - 87;
  } else if (n >= 65 and n <= 70) { n - 55 } else { 16 };
};

func hexBytes(hex : Text) : [Nat8] {
  let chars = Array.fromIter<Char>(Text.toIter(hex));
  assert chars.size() % 2 == 0;
  Array.tabulate<Nat8>(
    chars.size() / 2,
    func(i) = Nat8.fromNat(hexVal(chars[i * 2]) * 16 + hexVal(chars[i * 2 + 1])),
  );
};

func toHex(b : Blob) : Text {
  let digits = Array.fromIter<Char>(Text.toIter("0123456789abcdef"));
  var out = "";
  for (byte in Blob.toArray(b).vals()) {
    let n = Nat8.toNat(byte);
    out #= Char.toText(digits[n / 16]) # Char.toText(digits[n % 16]);
  };
  out;
};

// Big-endian, unlike `ic_bls12_381`'s little-endian `Scalar::to_bytes`; the
// generator flips it, and `transport public key matches` is what proves the
// flip is the right way round.
let TSK_BE = "167b736e44a1c134bd46ca834220c75c186768612568ac264a01554c46633e76";
let TPK = "911969d56f42875d37a92d7eaa5d43293eff9f9a20ba4c60523e70a695eaeadeb721659b52a49d74e67841ad19033a12";
let DPK = "972c4c6cc184b56121a1d27ef1ca3a2334d1a51be93573bd18e168f78f8fe15ce44fb029ffe8e9c3ee6bea2660f4f35e0774a35a80d6236c050fd8f831475b5e145116d3e83d26c533545f64b08464e4bcc755f990a381efa89804212d4eef5f";
let EK = "b1a13757eaae15a3c8884fc1a3453f8a29b88984418e65f1bd21042ce1d6809b2f8a49f7326c1327f2a3921e8ff1d6c3adde2a801f1f88de98ccb40c62e366a279e7aec5875a0ce2f2a9f3e109d9cb193f0197eadb2c5f5568ee4d6a87e115910662e01e604087246be8b081fc6b8a06b4b0100ed1935d8c8d18d9f70d61718c5dba23a641487e72b3b25884eeede8feb3c71599bfbcebe60d29408795c85b4bdf19588c034d898e7fc513be8dbd04cac702a1672f5625f5833d063b05df7503";
let IDENTITY = "6d657373616765"; // b"message"
let VETKEY = "987db5406ce297e729c8564a106dc896943b00216a095fe9c5d32a16a330c02eb80e6f468ede83cde5462b5145b58f65";

func tsk() : Scalar.Scalar {
  switch (Scalar.fromBytes(hexBytes(TSK_BE))) {
    case (?s) s;
    case null { assert false; 0 };
  };
};

func dpk() : G2.Affine {
  switch (G2.fromCompressed(Array.toBlob(hexBytes(DPK)))) {
    case (?p) p;
    case null { assert false; G2.affineIdentity };
  };
};

func ek() : VetKey.EncryptedVetKey {
  switch (VetKey.deserialize(hexBytes(EK))) {
    case (?k) k;
    case null { assert false; { c1 = G1.affineIdentity; c2 = G2.affineIdentity; c3 = G1.affineIdentity } };
  };
};

let identity = hexBytes(IDENTITY);

test(
  "the encrypted key parses into three valid points",
  func() {
    let k = ek();
    assert G1.isOnCurve(k.c1);
    assert G2.isOnCurve(k.c2);
    assert G1.isOnCurve(k.c3);
  },
);

test(
  "a reply of the wrong length is rejected",
  func() {
    assert VetKey.deserialize(hexBytes(EK) |> Array.sliceToArray<Nat8>(_, 0, 191)) == null;
    assert VetKey.deserialize([]) == null;
  },
);

test(
  "transport public key matches",
  func() {
    assert toHex(VetKey.transportPublicKey(tsk())) == TPK;
  },
);

test(
  "decryptAndVerify recovers the vetKey",
  func() {
    switch (VetKey.decryptAndVerify(ek(), tsk(), dpk(), identity)) {
      case (?k) assert toHex(G1.toCompressed(k)) == VETKEY;
      case null assert false;
    };
  },
);

test(
  "a wrong transport secret key is rejected",
  func() {
    // Unwrapping with the wrong scalar yields a point that is on the curve but
    // is not the signature, so only the BLS check can catch it.
    let wrong = Scalar.fromNat(tsk() + 1);
    assert VetKey.decryptAndVerify(ek(), wrong, dpk(), identity) == null;
  },
);

test(
  "a wrong identity is rejected",
  func() {
    assert VetKey.decryptAndVerify(ek(), tsk(), dpk(), hexBytes("6d657373616766")) == null;
  },
);

test(
  "a wrong derived public key is rejected",
  func() {
    // The DPK is what the canister derived from its own compiled-in master key.
    // Substituting another one is exactly the forgery this check exists to stop.
    let other = G2.toAffine(G2.mul(G2.fromAffine(G2.generator), 12345));
    assert VetKey.decryptAndVerify(ek(), tsk(), other, identity) == null;
  },
);

test(
  "an identity derived public key is rejected",
  func() {
    assert not VetKey.verifyBlsSignature(G2.affineIdentity, identity, G1.generator);
  },
);

test(
  "a tampered c3 is rejected",
  func() {
    let k = ek();
    let tampered = { k with c3 = G1.toAffine(G1.add(G1.fromAffine(k.c3), G1.fromAffine(G1.generator))) };
    assert VetKey.decryptAndVerify(tampered, tsk(), dpk(), identity) == null;
  },
);

test(
  "c1 inconsistent with c2 is rejected",
  func() {
    // The two share a discrete logarithm. Doubling only c1 breaks that, and the
    // first pairing check must catch it before any unwrapping happens.
    let k = ek();
    let tampered = { k with c1 = G1.toAffine(G1.double(G1.fromAffine(k.c1))) };
    assert VetKey.decryptAndVerify(tampered, tsk(), dpk(), identity) == null;
  },
);
