[package]
name = "sealed-secrets-canister"
description = "PoC canister that receives vetKD-sealed secrets and decrypts them in enclave memory"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-management-canister = { workspace = true }
ic-dummy-getrandom-for-wasm = "0.1.0"
ic-stable-structures = { workspace = true }
ic-vetkeys = { workspace = true }
sealed-secrets-core = { path = "../core" }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
