[package]
name = "sealed-secrets-bls"
version = "0.0.1"
description = "EXPERIMENTAL, UNAUDITED BLS12-381 for Motoko — PoC only, do not use in production"
repository = "https://github.com/marc0olo/icp-seeding-secrets-poc"
keywords = [ "bls12-381", "vetkeys", "experimental" ]
license = "Apache-2.0"

[dependencies]
core = "2.6.1"

[dev-dependencies]
test = "2.1.1"
bench = "2.0.1"

[toolchain]
moc = "1.13.0"
pocket-ic = "15.0.0"
