//! Emits BLS12-381 test vectors from the Rust reference implementation.
//!
//! The Motoko port asserts against these. That is the point: porting the
//! reference's own unit tests is not possible for the field layer, because those
//! tests are written against its internal Montgomery limb representation, which
//! the Motoko port deliberately does not share. What matters is not that the two
//! implementations compute alike internally, but that they **agree on values** —
//! so the vectors are generated from real curve points, through the same
//! serialization the protocol uses.
//!
//!     cargo run -p vectorgen > motoko/vetkeys/test/vectors.json
//!
//! Regenerate whenever `ic_bls12_381` is upgraded; a diff in the output is a
//! signal worth reading, not noise to commit past.

use ic_bls12_381::hash_to_curve::{ExpandMsgXmd, HashToCurve};
use ic_bls12_381::{G1Affine, G1Projective, G2Affine, G2Projective, Scalar};
use ic_vetkeys::{
    DerivedPublicKey, EncryptedVetKey, IbeCiphertext, IbeIdentity, IbeSeed, TransportSecretKey,
    VetKey,
};

/// Scalars chosen to cover the boring cases and the awkward ones: identity,
/// small values, a power of two, and something large and irregular.
const SCALARS: &[u64] = &[1, 2, 3, 7, 256, 65_537, 4_294_967_295, 1_234_567_890_123];

fn main() {
    println!("{{");
    println!("  \"_comment\": \"generated by `cargo run -p vectorgen` from ic_bls12_381 0.10.1 — do not edit\",");

    // The base field modulus, reassembled from the reference's limbs, so the
    // Motoko constant can be checked rather than trusted.
    println!("  \"fp_modulus_hex\": \"1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab\",");

    // G1: uncompressed is x || y, 48 big-endian bytes each. Every point here
    // satisfies y^2 = x^3 + 4 over F_p, which is what the Motoko tests check —
    // exercising the modulus, add, mul and square together against real data.
    println!("  \"g1\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G1Affine::from(G1Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x\": \"{}\", \"y\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[..48]),
            hex::encode(&unc[48..]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // G2 coordinates live in F_p2, serialized as c1 || c0 per component.
    println!("  \"g2\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G2Affine::from(G2Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x_c1\": \"{}\", \"x_c0\": \"{}\", \"y_c1\": \"{}\", \"y_c0\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[0..48]),
            hex::encode(&unc[48..96]),
            hex::encode(&unc[96..144]),
            hex::encode(&unc[144..192]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // The identity, which every implementation gets wrong at least once.
    println!(
        "  \"g1_identity_compressed\": \"{}\",",
        hex::encode(G1Affine::identity().to_compressed())
    );
    println!(
        "  \"g2_identity_compressed\": \"{}\",",
        hex::encode(G2Affine::identity().to_compressed())
    );

    emit_hash_to_scalar_vectors();
    emit_hash_to_curve_vectors();
    emit_encrypted_vetkey_vector();
    emit_ibe_vector();

    println!("}}");
}

/// `hash_to_scalar` vectors.
///
/// The IBE scheme derives its per-message scalar this way, so the Motoko port
/// must agree byte for byte or nothing decrypts. This replicates
/// `ic-vetkeys`' private `hash_to_scalar` (`utils/mod.rs:245`) using the same
/// public primitive it calls.
fn emit_hash_to_scalar_vectors() {
    use ic_bls12_381::hash_to_curve::HashToField;

    let cases: &[(&str, &str)] = &[
        ("", "ic-vetkd-bls12-381-ibe-hash-to-mask"),
        ("abc", "ic-vetkd-bls12-381-ibe-hash-to-mask"),
        (
            "a longer input than one hash block, to exercise the expansion loop properly",
            "ic-vetkd-bls12-381-ibe-hash-to-mask",
        ),
    ];

    println!("  \"hash_to_scalar\": [");
    let mut first = true;
    for (input, dst) in cases {
        let mut s = [Scalar::zero()];
        <Scalar as HashToField>::hash_to_field::<ExpandMsgXmd<sha2::Sha256>>(
            input.as_bytes(),
            dst.as_bytes(),
            &mut s,
        );
        if !first {
            println!(",");
        }
        first = false;
        // Scalar::to_bytes is little-endian; reverse for the big-endian form
        // the Motoko port uses.
        let mut le = s[0].to_bytes();
        le.reverse();
        print!(
            "    {{ \"input\": \"{}\", \"dst\": \"{}\", \"scalar_be\": \"{}\" }}",
            input,
            dst,
            hex::encode(le)
        );
    }
    println!("\n  ],");
}

/// `hash_to_curve` vectors for G1, with the domain separator ic-vetkeys uses for
/// vetKey verification (`utils/mod.rs:1396`).
///
/// This is the last piece the Motoko port needs to reach parity with the Rust
/// canister, which verifies that a vetKey is a genuine BLS signature before
/// using it.
fn emit_hash_to_curve_vectors() {
    const DST: &[u8] = b"BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_AUG_";

    println!("  \"hash_to_curve_g1\": [");
    let mut first = true;
    for msg in [
        "",
        "abc",
        "a message long enough to need more than one expansion block here",
    ] {
        let p = <G1Projective as HashToCurve<ExpandMsgXmd<sha2::Sha256>>>::hash_to_curve(
            msg.as_bytes(),
            DST,
        );
        let a = G1Affine::from(p);
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"msg\": \"{}\", \"compressed\": \"{}\" }}",
            msg,
            hex::encode(a.to_compressed())
        );
    }
    println!("\n  ],");
    println!(
        "  \"hash_to_curve_g1_dst\": \"{}\",",
        String::from_utf8_lossy(DST)
    );
}

/// The finish line for the Motoko port: a complete, valid IBE triple.
///
/// Everything here is generated offline by playing the role of the subnet — pick
/// a master secret, derive the public key from it, and produce the vetKey as the
/// BLS signature over the identity that the subnet would have produced. The
/// resulting ciphertext is indistinguishable from a real one, because it *is*
/// one: the same `IbeCiphertext::encrypt` the client uses.
///
/// When the Motoko implementation can turn `vetkey` + `ciphertext` back into
/// `plaintext`, the port works. Nothing short of that proves it.
fn emit_ibe_vector() {
    // Stand in for the subnet's master key. Fixed, so the vector is stable.
    // (The digits spell "sealed sec" — grouped conventionally because clippy's
    // unusual_byte_groupings lint is right that cleverness costs readability.)
    let msk = Scalar::from(0x0005_ea1e_d5ec_4e75_u64);
    let mpk = G2Affine::from(G2Projective::generator() * msk);

    let dpk = DerivedPublicKey::deserialize(&mpk.to_compressed())
        .expect("master public key should parse as a derived public key");

    let identity = b"icp-sealed-secrets-v1-demo-identity";
    let plaintext = b"a sealed secret";

    // The vetKey IS a BLS signature: H(pk || identity) * msk, with the augmented
    // domain separator ic-vetkeys uses (utils/mod.rs:1396).
    let mut signature_input = Vec::new();
    signature_input.extend_from_slice(&mpk.to_compressed());
    signature_input.extend_from_slice(identity);
    let h = <G1Projective as HashToCurve<ExpandMsgXmd<sha2::Sha256>>>::hash_to_curve(
        signature_input,
        b"BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_AUG_",
    );
    let signature = G1Affine::from(h * msk);
    let vetkey = VetKey::deserialize(&signature.to_compressed()).expect("valid vetkey");

    // A fixed seed keeps the ciphertext reproducible run to run.
    let seed = IbeSeed::from_bytes(&[0x42u8; 32]).expect("valid seed");
    let ciphertext =
        IbeCiphertext::encrypt(&dpk, &IbeIdentity::from_bytes(identity), plaintext, &seed);

    // Prove the triple is self-consistent before emitting it. A vector that does
    // not decrypt in Rust would send the Motoko port chasing a phantom.
    let recovered = ciphertext
        .decrypt(&vetkey)
        .expect("the vector must decrypt");
    assert_eq!(
        recovered, plaintext,
        "generated vector is not self-consistent"
    );

    println!("  \"ibe\": {{");
    println!("    \"_comment\": \"decrypting ciphertext with vetkey must yield plaintext\",");
    println!(
        "    \"derived_public_key\": \"{}\",",
        hex::encode(dpk.serialize())
    );
    println!(
        "    \"identity_utf8\": \"{}\",",
        String::from_utf8_lossy(identity)
    );
    println!("    \"vetkey\": \"{}\",", hex::encode(vetkey.serialize()));
    println!(
        "    \"ciphertext\": \"{}\",",
        hex::encode(ciphertext.serialize())
    );
    println!(
        "    \"plaintext_utf8\": \"{}\"",
        String::from_utf8_lossy(plaintext)
    );
    println!("  }}");
}

/// A real `vetkd_derive_key` reply, so `decryptAndVerify` is checked against
/// output the subnet actually produced rather than against a re-derivation of
/// this file's own assumptions.
///
/// The values are lifted verbatim from `ic-vetkeys`' own
/// `transport_key_works_with_bls_and_ibe` (`tests/utils.rs:245`), where they are
/// annotated "generated by internal library" — that is, by the threshold
/// implementation running in the replica, not by this crate. They are the
/// closest thing to ground truth available offline.
fn emit_encrypted_vetkey_vector() {
    const TSK: &str = "763e63464c55014a26ac6825616867185cc7204283ca46bd34c1a1446e737b16";
    const TPK: &str = "911969d56f42875d37a92d7eaa5d43293eff9f9a20ba4c60523e70a695eaeadeb721659b52a49d74e67841ad19033a12";
    const DPK: &str = "972c4c6cc184b56121a1d27ef1ca3a2334d1a51be93573bd18e168f78f8fe15ce44fb029ffe8e9c3ee6bea2660f4f35e0774a35a80d6236c050fd8f831475b5e145116d3e83d26c533545f64b08464e4bcc755f990a381efa89804212d4eef5f";
    const EK: &str = "b1a13757eaae15a3c8884fc1a3453f8a29b88984418e65f1bd21042ce1d6809b2f8a49f7326c1327f2a3921e8ff1d6c3adde2a801f1f88de98ccb40c62e366a279e7aec5875a0ce2f2a9f3e109d9cb193f0197eadb2c5f5568ee4d6a87e115910662e01e604087246be8b081fc6b8a06b4b0100ed1935d8c8d18d9f70d61718c5dba23a641487e72b3b25884eeede8feb3c71599bfbcebe60d29408795c85b4bdf19588c034d898e7fc513be8dbd04cac702a1672f5625f5833d063b05df7503";
    // b"message"
    const IDENTITY: &str = "6d657373616765";

    let tsk = TransportSecretKey::deserialize(&hex::decode(TSK).unwrap()).expect("valid tsk");
    let dpk = DerivedPublicKey::deserialize(&hex::decode(DPK).unwrap()).expect("valid dpk");
    let ek = EncryptedVetKey::deserialize(&hex::decode(EK).unwrap()).expect("valid encrypted key");
    let identity = hex::decode(IDENTITY).unwrap();

    assert_eq!(hex::encode(tsk.public_key()), TPK, "tsk does not match tpk");

    let vetkey = ek
        .decrypt_and_verify(&tsk, &dpk, &identity)
        .expect("the vector must decrypt and verify");

    // `ic_bls12_381` serializes a scalar little-endian; the Motoko port is
    // big-endian throughout (`Scalar.fromBytes`). Emitting the flipped form
    // keeps the endianness conversion here, where it can be stated, rather than
    // in the port where it would look like an arbitrary reversal. The pinned
    // `transport_public_key` is what proves the flip is the right way round.
    let mut tsk_be = tsk.serialize();
    tsk_be.reverse();

    println!("  \"encrypted_vetkey\": {{");
    println!(
        "    \"_comment\": \"real vetkd_derive_key reply, from ic-vetkeys tests/utils.rs:245\","
    );
    println!(
        "    \"transport_secret_key_be\": \"{}\",",
        hex::encode(&tsk_be)
    );
    println!("    \"transport_public_key\": \"{TPK}\",");
    println!("    \"derived_public_key\": \"{DPK}\",");
    println!("    \"encrypted_key\": \"{EK}\",");
    println!("    \"identity\": \"{IDENTITY}\",");
    println!(
        "    \"vetkey\": \"{}\"",
        hex::encode(vetkey.signature_bytes())
    );
    println!("  }},");
}
