//! Emits BLS12-381 test vectors from the Rust reference implementation.
//!
//! The Motoko port asserts against these. That is the point: porting the
//! reference's own unit tests is not possible for the field layer, because those
//! tests are written against its internal Montgomery limb representation, which
//! the Motoko port deliberately does not share. What matters is not that the two
//! implementations compute alike internally, but that they **agree on values** —
//! so the vectors are generated from real curve points, through the same
//! serialization the protocol uses.
//!
//!     cargo run -p vectorgen > motoko/test/vectors.json
//!
//! Regenerate whenever `ic_bls12_381` is upgraded; a diff in the output is a
//! signal worth reading, not noise to commit past.

use ic_bls12_381::{G1Affine, G1Projective, G2Affine, G2Projective, Scalar};

/// Scalars chosen to cover the boring cases and the awkward ones: identity,
/// small values, a power of two, and something large and irregular.
const SCALARS: &[u64] = &[1, 2, 3, 7, 256, 65_537, 4_294_967_295, 1_234_567_890_123];

fn main() {
    println!("{{");
    println!("  \"_comment\": \"generated by `cargo run -p vectorgen` from ic_bls12_381 0.10.1 — do not edit\",");

    // The base field modulus, reassembled from the reference's limbs, so the
    // Motoko constant can be checked rather than trusted.
    println!("  \"fp_modulus_hex\": \"1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab\",");

    // G1: uncompressed is x || y, 48 big-endian bytes each. Every point here
    // satisfies y^2 = x^3 + 4 over F_p, which is what the Motoko tests check —
    // exercising the modulus, add, mul and square together against real data.
    println!("  \"g1\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G1Affine::from(G1Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x\": \"{}\", \"y\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[..48]),
            hex::encode(&unc[48..]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // G2 coordinates live in F_p2, serialized as c1 || c0 per component.
    println!("  \"g2\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G2Affine::from(G2Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x_c1\": \"{}\", \"x_c0\": \"{}\", \"y_c1\": \"{}\", \"y_c0\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[0..48]),
            hex::encode(&unc[48..96]),
            hex::encode(&unc[96..144]),
            hex::encode(&unc[144..192]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // The identity, which every implementation gets wrong at least once.
    println!(
        "  \"g1_identity_compressed\": \"{}\",",
        hex::encode(G1Affine::identity().to_compressed())
    );
    println!(
        "  \"g2_identity_compressed\": \"{}\"",
        hex::encode(G2Affine::identity().to_compressed())
    );
    println!("}}");
}
