//! Emits BLS12-381 test vectors from the Rust reference implementation.
//!
//! The Motoko port asserts against these. That is the point: porting the
//! reference's own unit tests is not possible for the field layer, because those
//! tests are written against its internal Montgomery limb representation, which
//! the Motoko port deliberately does not share. What matters is not that the two
//! implementations compute alike internally, but that they **agree on values** —
//! so the vectors are generated from real curve points, through the same
//! serialization the protocol uses.
//!
//!     cargo run -p vectorgen > motoko/test/vectors.json
//!
//! Regenerate whenever `ic_bls12_381` is upgraded; a diff in the output is a
//! signal worth reading, not noise to commit past.

use ic_bls12_381::hash_to_curve::{ExpandMsgXmd, HashToCurve};
use ic_bls12_381::{G1Affine, G1Projective, G2Affine, G2Projective, Scalar};
use ic_vetkeys::{DerivedPublicKey, IbeCiphertext, IbeIdentity, IbeSeed, VetKey};

/// Scalars chosen to cover the boring cases and the awkward ones: identity,
/// small values, a power of two, and something large and irregular.
const SCALARS: &[u64] = &[1, 2, 3, 7, 256, 65_537, 4_294_967_295, 1_234_567_890_123];

fn main() {
    println!("{{");
    println!("  \"_comment\": \"generated by `cargo run -p vectorgen` from ic_bls12_381 0.10.1 — do not edit\",");

    // The base field modulus, reassembled from the reference's limbs, so the
    // Motoko constant can be checked rather than trusted.
    println!("  \"fp_modulus_hex\": \"1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab\",");

    // G1: uncompressed is x || y, 48 big-endian bytes each. Every point here
    // satisfies y^2 = x^3 + 4 over F_p, which is what the Motoko tests check —
    // exercising the modulus, add, mul and square together against real data.
    println!("  \"g1\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G1Affine::from(G1Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x\": \"{}\", \"y\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[..48]),
            hex::encode(&unc[48..]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // G2 coordinates live in F_p2, serialized as c1 || c0 per component.
    println!("  \"g2\": [");
    let mut first = true;
    for &k in SCALARS {
        let p = G2Affine::from(G2Projective::generator() * Scalar::from(k));
        let unc = p.to_uncompressed();
        let comp = p.to_compressed();
        if !first {
            println!(",");
        }
        first = false;
        print!(
            "    {{ \"scalar\": {}, \"x_c1\": \"{}\", \"x_c0\": \"{}\", \"y_c1\": \"{}\", \"y_c0\": \"{}\", \"compressed\": \"{}\" }}",
            k,
            hex::encode(&unc[0..48]),
            hex::encode(&unc[48..96]),
            hex::encode(&unc[96..144]),
            hex::encode(&unc[144..192]),
            hex::encode(comp)
        );
    }
    println!("\n  ],");

    // The identity, which every implementation gets wrong at least once.
    println!(
        "  \"g1_identity_compressed\": \"{}\",",
        hex::encode(G1Affine::identity().to_compressed())
    );
    println!(
        "  \"g2_identity_compressed\": \"{}\",",
        hex::encode(G2Affine::identity().to_compressed())
    );

    emit_ibe_vector();

    println!("}}");
}

/// The finish line for the Motoko port: a complete, valid IBE triple.
///
/// Everything here is generated offline by playing the role of the subnet — pick
/// a master secret, derive the public key from it, and produce the vetKey as the
/// BLS signature over the identity that the subnet would have produced. The
/// resulting ciphertext is indistinguishable from a real one, because it *is*
/// one: the same `IbeCiphertext::encrypt` the client uses.
///
/// When the Motoko implementation can turn `vetkey` + `ciphertext` back into
/// `plaintext`, the port works. Nothing short of that proves it.
fn emit_ibe_vector() {
    // Stand in for the subnet's master key. Fixed, so the vector is stable.
    // (The digits spell "sealed sec" — grouped conventionally because clippy's
    // unusual_byte_groupings lint is right that cleverness costs readability.)
    let msk = Scalar::from(0x0005_ea1e_d5ec_4e75_u64);
    let mpk = G2Affine::from(G2Projective::generator() * msk);

    let dpk = DerivedPublicKey::deserialize(&mpk.to_compressed())
        .expect("master public key should parse as a derived public key");

    let identity = b"icp-sealed-secrets-v1-demo-identity";
    let plaintext = b"a sealed secret";

    // The vetKey IS a BLS signature: H(pk || identity) * msk, with the augmented
    // domain separator ic-vetkeys uses (utils/mod.rs:1396).
    let mut signature_input = Vec::new();
    signature_input.extend_from_slice(&mpk.to_compressed());
    signature_input.extend_from_slice(identity);
    let h = <G1Projective as HashToCurve<ExpandMsgXmd<sha2::Sha256>>>::hash_to_curve(
        signature_input,
        b"BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_AUG_",
    );
    let signature = G1Affine::from(h * msk);
    let vetkey = VetKey::deserialize(&signature.to_compressed()).expect("valid vetkey");

    // A fixed seed keeps the ciphertext reproducible run to run.
    let seed = IbeSeed::from_bytes(&[0x42u8; 32]).expect("valid seed");
    let ciphertext =
        IbeCiphertext::encrypt(&dpk, &IbeIdentity::from_bytes(identity), plaintext, &seed);

    // Prove the triple is self-consistent before emitting it. A vector that does
    // not decrypt in Rust would send the Motoko port chasing a phantom.
    let recovered = ciphertext
        .decrypt(&vetkey)
        .expect("the vector must decrypt");
    assert_eq!(
        recovered, plaintext,
        "generated vector is not self-consistent"
    );

    println!("  \"ibe\": {{");
    println!("    \"_comment\": \"decrypting ciphertext with vetkey must yield plaintext\",");
    println!(
        "    \"derived_public_key\": \"{}\",",
        hex::encode(dpk.serialize())
    );
    println!(
        "    \"identity_utf8\": \"{}\",",
        String::from_utf8_lossy(identity)
    );
    println!("    \"vetkey\": \"{}\",", hex::encode(vetkey.serialize()));
    println!(
        "    \"ciphertext\": \"{}\",",
        hex::encode(ciphertext.serialize())
    );
    println!(
        "    \"plaintext_utf8\": \"{}\"",
        String::from_utf8_lossy(plaintext)
    );
    println!("  }}");
}
