/* eslint-disable */

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

/**
 * Installation arguments.
 * 
 * Just the key name. The canister asks the subnet for its public key rather
 * than deriving it from a compiled-in constant, so the same build runs against
 * a local network and mainnet with nothing to configure — and nothing to get
 * wrong in a way that silently orphans every sealed ciphertext.
 */
export interface InitArgs {
  /**
   * vetKD key name, e.g. `key_1`.
   */
  'key_name' : string,
}
/**
 * Which table of hardcoded master public keys to check the subnet's answer
 * against.
 * 
 * This is a `self_test` *argument*, not configuration. The canister obtains its
 * public key from `vetkd_public_key`, which is authoritative; comparing that
 * against a constant compiled into this Wasm is an on-demand audit, and the
 * caller is the one who knows which network they believe they are on.
 */
export type KeySource = {
    /**
     * IC mainnet master keys.
     */
    'Mainnet' : null
  } |
  {
    /**
     * PocketIC master keys, which local `icp network` also uses.
     */
    'PocketIc' : null
  };
export type Result = { 'Ok' : SealedSecretInfo } |
  { 'Err' : SealedSecretsError };
export type Result_1 = { 'Ok' : Array<SealedSecretEntry> } |
  { 'Err' : SealedSecretsError };
export type Result_2 = { 'Ok' : SelfTestReport } |
  { 'Err' : SealedSecretsError };
export type Result_3 = { 'Ok' : bigint } |
  { 'Err' : SealedSecretsError };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : SealedSecretsError };
export type Result_5 = { 'Ok' : string } |
  { 'Err' : SealedSecretsError };
export type Result_6 = { 'Ok' : Uint8Array } |
  { 'Err' : SealedSecretsError };
/**
 * One stored secret, as reported by `list`. Carries nothing derived from the
 * plaintext: a digest of the plaintext would be an offline guessing oracle for
 * low-entropy secrets, whereas a digest of a randomised ciphertext reveals
 * nothing.
 */
export interface SealedSecretEntry {
  /**
   * SHA-256 of the ciphertext, so a client can confirm its upload landed.
   */
  'ciphertext_sha256' : Uint8Array,
  /**
   * Ciphertext length in bytes.
   */
  'ciphertext_len' : bigint,
  /**
   * The secret's name.
   */
  'name' : string,
  /**
   * Nanoseconds since the epoch when it was last overwritten.
   */
  'updated_at_ns' : bigint,
  /**
   * The epoch its ciphertext was sealed under.
   */
  'epoch' : number,
  /**
   * Nanoseconds since the epoch when this name was first set.
   */
  'created_at_ns' : bigint,
  /**
   * Increments on every overwrite. Also invalidates the plaintext cache.
   */
  'revision' : bigint,
}
/**
 * Everything a client needs in order to seal a secret for this canister, and
 * to check that it is sealing to the right key.
 */
export interface SealedSecretInfo {
  /**
   * The exact vetKD `context` bytes this canister derives under.
   */
  'context' : Uint8Array,
  /**
   * Largest number of secrets this canister will hold.
   */
  'max_secrets' : bigint,
  /**
   * The 96-byte derived public key to encrypt to.
   * 
   * A client must treat this as a *cross-check* against its own offline
   * derivation, never as the key to encrypt to. See `verify_reported_public_key`.
   */
  'public_key' : Uint8Array,
  /**
   * Largest ciphertext this canister will accept.
   */
  'max_ciphertext_len' : bigint,
  /**
   * The current epoch. New seals must target this value.
   */
  'epoch' : number,
  /**
   * The vetKD key name, e.g. `key_1`.
   */
  'key_name' : string,
  /**
   * The exact IBE identity bytes for the current epoch.
   */
  'identity' : Uint8Array,
  /**
   * Version of this interface. Currently 1.
   */
  'standard_version' : number,
}
/**
 * Typed errors, so that tooling can branch on the cause rather than parsing prose.
 */
export type SealedSecretsError = {
    /**
     * Anything else, with context.
     */
    'Internal' : string
  } |
  {
    /**
     * Storing this would exceed `max_secrets`.
     */
    'TooMany' : { 'max' : bigint }
  } |
  {
    /**
     * The blob is not a well-formed IBE ciphertext, or does not decrypt under
     * this canister's key — most often a wrong context, epoch or key id.
     */
    'InvalidCiphertext' : string
  } |
  {
    /**
     * Ciphertext exceeds `max_ciphertext_len`.
     */
    'TooLarge' : { 'max' : bigint }
  } |
  {
    /**
     * No secret by that name.
     */
    'NotFound' : null
  } |
  {
    /**
     * Caller is not a controller.
     */
    'Unauthorized' : null
  } |
  {
    /**
     * The name is empty, too long, or has characters outside `[A-Za-z0-9_.-]`.
     */
    'InvalidName' : string
  } |
  {
    /**
     * The subnet could not derive the key. Usually means this subnet does not
     * hold an NI-DKG transcript for the requested vetKD key.
     */
    'VetKdUnavailable' : { 'detail' : string, 'key_name' : string }
  };
/**
 * The result of `self_test`: a deploy-time health check that exercises the
 * whole decryption path so that failures surface here rather than during a
 * production call.
 */
export interface SelfTestReport {
  /**
   * The context actually in use.
   */
  'effective_context' : Uint8Array,
  /**
   * Whether the subnet's public key matched the master key compiled into this
   * Wasm, for the `expected_source` the caller supplied. `None` when the
   * caller supplied none, or when no master key is compiled in for this key
   * name under that source.
   * 
   * This is the one check in the design that is not the subnet vouching for
   * itself, so a deployment should run it once with the source it expects.
   */
  'public_key_matches_master' : [] | [boolean],
  /**
   * The current epoch.
   */
  'epoch' : number,
  /**
   * The key name actually in use, read from stable state rather than source.
   * 
   * `StableCell::init` keeps an existing value, so editing a constant and
   * upgrading is a silent no-op. Reporting the effective value is what makes
   * that visible.
   */
  'effective_key_name' : string,
  /**
   * How many secrets are stored.
   */
  'num_secrets' : bigint,
  /**
   * Names that failed to decrypt. Should always be empty.
   */
  'undecryptable' : Array<string>,
  /**
   * Whether `vetkd_derive_key` answered and verified.
   */
  'vetkd_derive_ok' : boolean,
  /**
   * Whether `vetkd_public_key` answered.
   */
  'vetkd_public_key_ok' : boolean,
}
export interface _SERVICE {
  /**
   * Everything a client needs to seal for this canister.
   * 
   * An update rather than a query, because `public_key` comes from
   * `vetkd_public_key` — authoritative for whichever subnet this canister is
   * actually on. It is cached, so only the first call pays for the round trip.
   * 
   * A client must treat `public_key` as a cross-check against its **own** offline
   * derivation, never as the key to encrypt to. That comparison is the real
   * defence: this response crosses boundary nodes, and a client that trusted it
   * could be handed a key an attacker controls.
   */
  'icp_sealed_secret_info' : ActorMethod<[], Result>,
  /**
   * Lists stored secrets.
   * 
   * Controller-gated, because it is more revealing than it looks: IBE overhead is
   * a fixed 136 bytes, so `ciphertext_len` gives the exact plaintext length, and
   * the names alone (`billing_live_key`, …) are useful reconnaissance.
   * 
   * Nothing here is derived from a plaintext. A digest of the plaintext would be
   * an offline guessing oracle for low-entropy secrets; a digest of a randomised
   * ciphertext reveals nothing, while still letting a client confirm its upload
   * landed.
   */
  'icp_sealed_secret_list' : ActorMethod<[], Result_1>,
  /**
   * Exercises the full decryption path and reports what actually happened.
   * 
   * Run this right after deploying and after every upgrade. It is the difference
   * between finding out at deploy time that this subnet does not hold the vetKD
   * key, and finding out during a customer request.
   * 
   * Pass `expected_source` to also audit the subnet's `vetkd_public_key` against a
   * master key compiled into this Wasm — the one check in the whole design that is
   * not the subnet vouching for itself. Do this once per deployment with the
   * network you believe you are on.
   */
  'icp_sealed_secret_self_test' : ActorMethod<[[] | [KeySource]], Result_2>,
  /**
   * Stores a sealed secret, after proving it can actually be decrypted.
   * 
   * The trial decryption is the whole point of making this `async` rather than a
   * cheap synchronous write. Without it, a ciphertext sealed under the wrong
   * context, epoch or key id is accepted happily and only discovered to be
   * unreadable at the first production use, potentially months later.
   * 
   * Returns the new revision.
   */
  'icp_sealed_secret_set' : ActorMethod<[string, Uint8Array], Result_3>,
  /**
   * Removes a secret and drops its cached plaintext.
   */
  'icp_sealed_secret_unset' : ActorMethod<[string], Result_4>,
  /**
   * Demonstrates the intended shape of *using* a secret: the plaintext is read
   * inside the canister and only a derived result leaves it.
   * 
   * A real canister would put the value in an outcall header here. Read the
   * README's HTTPS-outcalls note first — the request context, headers included,
   * enters replicated state on every node, so that is only safe on a uniformly
   * SEV-SNP subnet.
   * 
   * The length is not a new disclosure: `list` already reveals it, since IBE
   * overhead is a fixed 136 bytes.
   */
  'secret_len' : ActorMethod<[string], Result_3>,
  /**
   * Returns a decrypted secret **in the clear**. Requires the `test-hooks` feature.
   * 
   * It exists so you can see with your own eyes that decryption worked. It must
   * never be in a real deployment, and the reason is not that a controller could
   * not obtain the secret anyway — they can, by installing code that decrypts, or
   * by reading the heap out of a snapshot.
   * 
   * The reason is that this endpoint:
   * 
   * 1. **sends the plaintext to a boundary node.** The reply is not encrypted
   * end-to-end; the boundary node terminates TLS and is outside the subnet's
   * SEV-SNP trust boundary entirely. That undoes, in the outbound direction,
   * exactly what sealing achieved on the way in.
   * 2. **destroys the property that makes the code auditable.** "The published
   * code never returns the plaintext" is a claim a reader can verify by
   * reading it. Replace it with "…unless the caller is a controller" and the
   * guarantee now rests on the controller set being, and remaining, what you
   * think it is.
   * 3. **leaves no trace.** Installing code that leaks changes the module hash,
   * which is visible in the state tree. A call to this leaves nothing behind.
   * 
   * If you must observe a secret in production, don't: use `secret_sha256` under
   * the same feature and compare against a value you already hold.
   */
  'secret_reveal' : ActorMethod<[string], Result_5>,
  /**
   * SHA-256 of a decrypted secret. **Requires the `test-hooks` feature.**
   * 
   * Lets a test prove the canister recovered the exact plaintext without any
   * endpoint returning one. Still an oracle for a guessed value, hence
   * controller-gated and feature-gated.
   */
  'secret_sha256' : ActorMethod<[string], Result_6>,
}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const InitArgs = IDL.Record({ 'key_name' : IDL.Text });
  const SealedSecretInfo = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'max_secrets' : IDL.Nat64,
    'public_key' : IDL.Vec(IDL.Nat8),
    'max_ciphertext_len' : IDL.Nat64,
    'epoch' : IDL.Nat32,
    'key_name' : IDL.Text,
    'identity' : IDL.Vec(IDL.Nat8),
    'standard_version' : IDL.Nat32,
  });
  const SealedSecretsError = IDL.Variant({
    'Internal' : IDL.Text,
    'TooMany' : IDL.Record({ 'max' : IDL.Nat64 }),
    'InvalidCiphertext' : IDL.Text,
    'TooLarge' : IDL.Record({ 'max' : IDL.Nat64 }),
    'NotFound' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'InvalidName' : IDL.Text,
    'VetKdUnavailable' : IDL.Record({
      'detail' : IDL.Text,
      'key_name' : IDL.Text,
    }),
  });
  const Result = IDL.Variant({
    'Ok' : SealedSecretInfo,
    'Err' : SealedSecretsError,
  });
  const SealedSecretEntry = IDL.Record({
    'ciphertext_sha256' : IDL.Vec(IDL.Nat8),
    'ciphertext_len' : IDL.Nat64,
    'name' : IDL.Text,
    'updated_at_ns' : IDL.Nat64,
    'epoch' : IDL.Nat32,
    'created_at_ns' : IDL.Nat64,
    'revision' : IDL.Nat64,
  });
  const Result_1 = IDL.Variant({
    'Ok' : IDL.Vec(SealedSecretEntry),
    'Err' : SealedSecretsError,
  });
  const KeySource = IDL.Variant({
    'Mainnet' : IDL.Null,
    'PocketIc' : IDL.Null,
  });
  const SelfTestReport = IDL.Record({
    'effective_context' : IDL.Vec(IDL.Nat8),
    'public_key_matches_master' : IDL.Opt(IDL.Bool),
    'epoch' : IDL.Nat32,
    'effective_key_name' : IDL.Text,
    'num_secrets' : IDL.Nat64,
    'undecryptable' : IDL.Vec(IDL.Text),
    'vetkd_derive_ok' : IDL.Bool,
    'vetkd_public_key_ok' : IDL.Bool,
  });
  const Result_2 = IDL.Variant({
    'Ok' : SelfTestReport,
    'Err' : SealedSecretsError,
  });
  const Result_3 = IDL.Variant({
    'Ok' : IDL.Nat64,
    'Err' : SealedSecretsError,
  });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : SealedSecretsError });
  const Result_5 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : SealedSecretsError });
  const Result_6 = IDL.Variant({
    'Ok' : IDL.Vec(IDL.Nat8),
    'Err' : SealedSecretsError,
  });
  
  return IDL.Service({
    'icp_sealed_secret_info' : IDL.Func([], [Result], []),
    'icp_sealed_secret_list' : IDL.Func([], [Result_1], ['query']),
    'icp_sealed_secret_self_test' : IDL.Func(
        [IDL.Opt(KeySource)],
        [Result_2],
        [],
      ),
    'icp_sealed_secret_set' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result_3],
        [],
      ),
    'icp_sealed_secret_unset' : IDL.Func([IDL.Text], [Result_4], []),
    'secret_len' : IDL.Func([IDL.Text], [Result_3], []),
    'secret_reveal' : IDL.Func([IDL.Text], [Result_5], []),
    'secret_sha256' : IDL.Func([IDL.Text], [Result_6], []),
  });
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  const InitArgs = IDL.Record({ 'key_name' : IDL.Text });
  
  return [InitArgs];
};
