/* eslint-disable */

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

/**
 * # HTTP Header.
 * 
 * Represents a HTTP header.
 * 
 * See [`HttpRequestArgs::headers`] and [`HttpRequestResult::headers`].
 */
export interface HttpHeader {
  /**
   * Value of the header.
   */
  'value' : string,
  /**
   * Name of the header.
   */
  'name' : string,
}
/**
 * # HTTP Request Result
 * 
 * Result type of [`http_request`](https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-http_request).
 */
export interface HttpRequestResult {
  /**
   * The response status (e.g. 200, 404).
   */
  'status' : bigint,
  /**
   * The response’s body.
   */
  'body' : Uint8Array,
  /**
   * List of HTTP response headers and their corresponding values.
   */
  'headers' : Array<HttpHeader>,
}
/**
 * Installation arguments.
 * 
 * Just the key name. The canister asks the subnet for its public key rather
 * than deriving it from a compiled-in constant, so the same build runs against
 * a local network and mainnet with nothing to configure — and nothing to get
 * wrong in a way that silently orphans every sealed ciphertext.
 */
export interface InitArgs {
  /**
   * vetKD key name, e.g. `key_1`.
   */
  'key_name' : string,
}
export type Result = { 'Ok' : bigint } |
  { 'Err' : SealedSecretsError };
export type Result_1 = { 'Ok' : number } |
  { 'Err' : SealedSecretsError };
export type Result_2 = { 'Ok' : Array<SealedSecretEntry> } |
  { 'Err' : SealedSecretsError };
export type Result_3 = { 'Ok' : boolean } |
  { 'Err' : SealedSecretsError };
export type Result_4 = { 'Ok' : null } |
  { 'Err' : SealedSecretsError };
export type Result_5 = { 'Ok' : string } |
  { 'Err' : SealedSecretsError };
/**
 * One stored secret, as reported by `list`. Carries nothing derived from the
 * plaintext: a digest of the plaintext would be an offline guessing oracle for
 * low-entropy secrets, whereas a digest of a randomised ciphertext reveals
 * nothing.
 */
export interface SealedSecretEntry {
  /**
   * SHA-256 of the ciphertext that was submitted, so a client can confirm the
   * stored value is the one *it* uploaded.
   * 
   * Not a way to check the value is correct: IBE is randomised, so sealing
   * the same secret twice gives different digests. That question is
   * `icp_sealed_secret_matches`.
   */
  'ciphertext_sha256' : Uint8Array,
  /**
   * The secret's name.
   */
  'name' : string,
  /**
   * Nanoseconds since the epoch when it was last overwritten.
   */
  'updated_at_ns' : bigint,
  /**
   * Nanoseconds since the epoch when this name was first set.
   */
  'created_at_ns' : bigint,
  /**
   * Increments on every overwrite.
   */
  'revision' : bigint,
}
/**
 * Typed errors, so that tooling can branch on the cause rather than parsing prose.
 */
export type SealedSecretsError = {
    /**
     * Anything else, with context.
     */
    'Internal' : string
  } |
  {
    /**
     * The blob is not a well-formed IBE ciphertext, or does not decrypt under
     * this canister's key — most often a wrong key name or master key table.
     */
    'InvalidCiphertext' : string
  } |
  {
    /**
     * No secret by that name.
     */
    'NotFound' : null
  } |
  {
    /**
     * Caller is not a controller.
     */
    'Unauthorized' : null
  } |
  {
    /**
     * The name is empty, too long, or has characters outside `[A-Za-z0-9_.-]`.
     */
    'InvalidName' : string
  } |
  {
    /**
     * The subnet could not derive the key. Usually means this subnet does not
     * hold an NI-DKG transcript for the requested vetKD key.
     */
    'VetKdUnavailable' : { 'detail' : string, 'key_name' : string }
  };
/**
 * # Transform Args.
 * 
 * ```text
 * record {
 * response : http_response;
 * context : blob;
 * }
 * ```
 * 
 * See [`TransformContext`].
 */
export interface TransformArgs {
  /**
   * Context for response transformation
   */
  'context' : Uint8Array,
  /**
   * Raw response from remote service, to be transformed
   */
  'response' : HttpRequestResult,
}
export interface _SERVICE {
  /**
   * Measures what an IBE decryption costs in this canister, in instructions.
   * **Requires the `test-hooks` feature.**
   * 
   * Exists so the Rust and Motoko implementations can be compared on the same
   * footing. Native benchmarks are not comparable — what matters is the
   * instruction count the replica charges, and that is wasm-specific.
   * 
   * Takes the vetKey and ciphertext as arguments so both implementations can be
   * pointed at the identical vector from `motoko/vectors.json`.
   * 
   * **The first call costs about three times the rest.** `ic-vetkeys` holds a
   * `lazy_static` precomputed multiplication table for the `G2` generator
   * (`utils/mod.rs:219`), built on first use and reused thereafter. Quote the
   * steady-state figure when comparing, and remember the Motoko port has no such
   * table — a plain double-and-add ladder — so the gap is partly a missing
   * optimisation rather than a property of the language.
   */
  'bench_ibe_decrypt' : ActorMethod<[Uint8Array, Uint8Array], Result>,
  /**
   * The actual use case: authenticate an outbound HTTPS request with a sealed
   * secret, without the secret ever leaving the canister.
   * 
   * This is what the whole exercise is for, so read it as the template.
   * 
   * The sealed secret is the **complete `Authorization` header value**, not just a
   * token, so it works for any scheme — `Bearer ghp_…`, `Basic dXNlcjpwYXNz`, or
   * whatever an API expects — without this code baking one in.
   * 
   * Seal the correct credential and this returns `200`; seal a wrong one and it
   * returns `401`. That both branches are observable is the point: it proves the
   * secret's *value* reached the API and was evaluated, not merely that a request
   * went out.
   * 
   * **The endpoint is a constant, not a parameter.** A `call_api(url, ...)` taking
   * the URL from the caller would be an exfiltration primitive: point it at a
   * server you control and the secret is yours. A controller could achieve that
   * anyway by installing code, but shipping the capability as an endpoint is
   * gratuitous, and real canisters call a known API rather than an arbitrary one.
   * 
   * **Only the status code comes back.** Returning the body would be a mistake
   * waiting to happen: plenty of endpoints echo request headers (`/headers`,
   * `/anything`, most debug routes), and echoing our own `Authorization` header
   * back through the reply would undo the sealing entirely.
   * 
   * **The transform is mandatory, not decoration.** Every node performs this call
   * independently and consensus requires byte-identical responses, so anything
   * varying per node — `Date`, request ids, cookies — must be stripped or the call
   * fails.
   * 
   * Note the exposure, which the README covers in full: the request context,
   * headers included, enters replicated state on **every** node of the subnet
   * before any of them executes the call. On a SEV-SNP subnet that memory and the
   * checkpoints behind it are encrypted; on any other subnet the secret is
   * readable by every node operator the moment this runs.
   */
  'call_api_with_secret' : ActorMethod<[string, string], Result_1>,
  /**
   * Lists stored secrets: the inventory, and how a client confirms its write
   * landed.
   * 
   * Controller-gated, because names alone (`billing_live_key`, …) are useful
   * reconnaissance.
   * 
   * Nothing here is derived from a plaintext. A digest of the plaintext would be
   * an offline guessing oracle for low-entropy secrets; a digest of a randomised
   * ciphertext reveals nothing, while still letting the client that produced it
   * recognise its own upload.
   */
  'icp_sealed_secret_list' : ActorMethod<[], Result_2>,
  /**
   * Answers "is the value I hold the one you have stored?" without either side
   * disclosing it.
   * 
   * The caller seals its candidate exactly as it would for `set` — a fresh IBE
   * seed, so the ciphertext is unlinkable to any other — and the canister decrypts
   * both and compares in constant time. One bit comes back.
   * 
   * This is the endpoint an operator should reach for when they want to confirm
   * the right secret is deployed, and it is deliberately *not* "return me a
   * digest of the plaintext":
   * 
   * - a digest of a low-entropy secret is brute-forceable offline by anyone who
   * sees it, and replies cross a boundary node in the clear;
   * - the caller already knows the value they are checking, so a boolean tells
   * them everything a digest would;
   * - a ciphertext discloses nothing in the request direction either, whereas
   * sending `sha256(expected)` would put the same brute-forceable digest on the
   * wire.
   * 
   * Controller-gated, because for anyone else it is an oracle for confirming
   * guesses. For a controller it discloses nothing new — they can already read
   * the secret by installing code that decrypts it.
   */
  'icp_sealed_secret_matches' : ActorMethod<[string, Uint8Array], Result_3>,
  /**
   * Stores a sealed secret, after proving it can actually be decrypted.
   * 
   * The decryption is the whole point of making this `async` rather than a cheap
   * synchronous write. Without it, a ciphertext sealed to the wrong canister id,
   * key name or master key table is accepted happily and only discovered to be
   * unreadable at the first production use, potentially months later. It is also
   * the only health check this interface needs: it exercises `vetkd_public_key`,
   * `vetkd_derive_key`, verification and decryption, on real data.
   * 
   * Returns the new revision.
   */
  'icp_sealed_secret_set' : ActorMethod<[string, Uint8Array], Result>,
  /**
   * Removes a secret.
   */
  'icp_sealed_secret_unset' : ActorMethod<[string], Result_4>,
  /**
   * Returns a decrypted secret **in the clear**. Requires the `test-hooks` feature.
   * 
   * It exists so you can see with your own eyes that decryption worked. It must
   * never be in a real deployment, and the reason is not that a controller could
   * not obtain the secret anyway — they can, by installing code that decrypts, or
   * by reading the heap out of a snapshot.
   * 
   * The reason is that this endpoint:
   * 
   * 1. **sends the plaintext to a boundary node.** The reply is not encrypted
   * end-to-end; the boundary node terminates TLS and is outside the subnet's
   * SEV-SNP trust boundary entirely. That undoes, in the outbound direction,
   * exactly what sealing achieved on the way in.
   * 2. **destroys the property that makes the code auditable.** "The published
   * code never returns the plaintext" is a claim a reader can verify by
   * reading it. Replace it with "…unless the caller is a controller" and the
   * guarantee now rests on the controller set being, and remaining, what you
   * think it is.
   * 3. **leaves no trace.** Installing code that leaks changes the module hash,
   * which is visible in the state tree. A call to this leaves nothing behind.
   * 
   * If you want to confirm the right secret is deployed, use
   * `icp_sealed_secret_matches` instead — it answers the same question with one
   * bit and is safe to keep in a production build.
   */
  'secret_reveal' : ActorMethod<[string], Result_5>,
  /**
   * Makes an HTTP response deterministic across the nodes that fetched it.
   * 
   * Drops every response header — they carry `Date`, request ids and cookies that
   * differ per node, which would break consensus — and, incidentally, stops an
   * endpoint that echoes our `Authorization` header from smuggling the secret into
   * replicated state.
   * 
   * **This passes the body through unchanged, which is only safe because the demo
   * endpoint returns a constant.** If yours returns a timestamp, a request id or
   * anything else that differs between fetches, normalise it here too — parse out
   * the fields you need and drop the rest. Local testing will not catch this:
   * PocketIC issues exactly one request, so a varying body agrees with itself,
   * while on mainnet every node fetches independently and the call fails.
   */
  'strip_response' : ActorMethod<[TransformArgs], HttpRequestResult>,
}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const InitArgs = IDL.Record({ 'key_name' : IDL.Text });
  const SealedSecretsError = IDL.Variant({
    'Internal' : IDL.Text,
    'InvalidCiphertext' : IDL.Text,
    'NotFound' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'InvalidName' : IDL.Text,
    'VetKdUnavailable' : IDL.Record({
      'detail' : IDL.Text,
      'key_name' : IDL.Text,
    }),
  });
  const Result = IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : SealedSecretsError });
  const Result_1 = IDL.Variant({
    'Ok' : IDL.Nat16,
    'Err' : SealedSecretsError,
  });
  const SealedSecretEntry = IDL.Record({
    'ciphertext_sha256' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'updated_at_ns' : IDL.Nat64,
    'created_at_ns' : IDL.Nat64,
    'revision' : IDL.Nat64,
  });
  const Result_2 = IDL.Variant({
    'Ok' : IDL.Vec(SealedSecretEntry),
    'Err' : SealedSecretsError,
  });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Bool, 'Err' : SealedSecretsError });
  const Result_4 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : SealedSecretsError });
  const Result_5 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : SealedSecretsError });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  
  return IDL.Service({
    'bench_ibe_decrypt' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'call_api_with_secret' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'icp_sealed_secret_list' : IDL.Func([], [Result_2], ['query']),
    'icp_sealed_secret_matches' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result_3],
        [],
      ),
    'icp_sealed_secret_set' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'icp_sealed_secret_unset' : IDL.Func([IDL.Text], [Result_4], []),
    'secret_reveal' : IDL.Func([IDL.Text], [Result_5], []),
    'strip_response' : IDL.Func(
        [TransformArgs],
        [HttpRequestResult],
        ['query'],
      ),
  });
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  const InitArgs = IDL.Record({ 'key_name' : IDL.Text });
  
  return [InitArgs];
};
