/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./sealed_secrets_canister.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export type Result_2 = {
    __kind__: "Ok";
    Ok: SelfTestReport;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export type Result = {
    __kind__: "Ok";
    Ok: SealedSecretInfo;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export type Result_6 = {
    __kind__: "Ok";
    Ok: Uint8Array;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export interface SealedSecretEntry {
    /**
     * SHA-256 of the ciphertext, so a client can confirm its upload landed.
     */
    ciphertext_sha256: Uint8Array;
    /**
     * Ciphertext length in bytes.
     */
    ciphertext_len: bigint;
    /**
     * The secret's name.
     */
    name: string;
    /**
     * Nanoseconds since the epoch when it was last overwritten.
     */
    updated_at_ns: bigint;
    /**
     * The epoch its ciphertext was sealed under.
     */
    epoch: number;
    /**
     * Nanoseconds since the epoch when this name was first set.
     */
    created_at_ns: bigint;
    /**
     * Increments on every overwrite. Also invalidates the plaintext cache.
     */
    revision: bigint;
}
export interface InitArgs {
    /**
     * vetKD key name, e.g. `key_1`.
     */
    key_name: string;
}
export type SealedSecretsError = {
    __kind__: "Internal";
    /**
     * Anything else, with context.
     */
    Internal: string;
} | {
    __kind__: "TooMany";
    /**
     * Storing this would exceed `max_secrets`.
     */
    TooMany: {
        max: bigint;
    };
} | {
    __kind__: "InvalidCiphertext";
    /**
     * The blob is not a well-formed IBE ciphertext, or does not decrypt under
     * this canister's key — most often a wrong context, epoch or key id.
     */
    InvalidCiphertext: string;
} | {
    __kind__: "TooLarge";
    /**
     * Ciphertext exceeds `max_ciphertext_len`.
     */
    TooLarge: {
        max: bigint;
    };
} | {
    __kind__: "NotFound";
    /**
     * No secret by that name.
     */
    NotFound: null;
} | {
    __kind__: "Unauthorized";
    /**
     * Caller is not a controller.
     */
    Unauthorized: null;
} | {
    __kind__: "InvalidName";
    /**
     * The name is empty, too long, or has characters outside `[A-Za-z0-9_.-]`.
     */
    InvalidName: string;
} | {
    __kind__: "VetKdUnavailable";
    /**
     * The subnet could not derive the key. Usually means this subnet does not
     * hold an NI-DKG transcript for the requested vetKD key.
     */
    VetKdUnavailable: {
        detail: string;
        key_name: string;
    };
};
export interface SelfTestReport {
    /**
     * The context actually in use.
     */
    effective_context: Uint8Array;
    /**
     * Whether the subnet's public key matched the master key compiled into this
     * Wasm, for the `expected_source` the caller supplied. `None` when the
     * caller supplied none, or when no master key is compiled in for this key
     * name under that source.
     * 
     * This is the one check in the design that is not the subnet vouching for
     * itself, so a deployment should run it once with the source it expects.
     */
    public_key_matches_master?: boolean;
    /**
     * The current epoch.
     */
    epoch: number;
    /**
     * The key name actually in use, read from stable state rather than source.
     * 
     * `StableCell::init` keeps an existing value, so editing a constant and
     * upgrading is a silent no-op. Reporting the effective value is what makes
     * that visible.
     */
    effective_key_name: string;
    /**
     * How many secrets are stored.
     */
    num_secrets: bigint;
    /**
     * Names that failed to decrypt. Should always be empty.
     */
    undecryptable: Array<string>;
    /**
     * Whether `vetkd_derive_key` answered and verified.
     */
    vetkd_derive_ok: boolean;
    /**
     * Whether `vetkd_public_key` answered.
     */
    vetkd_public_key_ok: boolean;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export type Result_1 = {
    __kind__: "Ok";
    Ok: Array<SealedSecretEntry>;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
};
export interface SealedSecretInfo {
    /**
     * The exact vetKD `context` bytes this canister derives under.
     */
    context: Uint8Array;
    /**
     * Largest number of secrets this canister will hold.
     */
    max_secrets: bigint;
    /**
     * The 96-byte derived public key to encrypt to.
     * 
     * A client must treat this as a *cross-check* against its own offline
     * derivation, never as the key to encrypt to. See `verify_reported_public_key`.
     */
    public_key: Uint8Array;
    /**
     * Largest ciphertext this canister will accept.
     */
    max_ciphertext_len: bigint;
    /**
     * The current epoch. New seals must target this value.
     */
    epoch: number;
    /**
     * The vetKD key name, e.g. `key_1`.
     */
    key_name: string;
    /**
     * The exact IBE identity bytes for the current epoch.
     */
    identity: Uint8Array;
    /**
     * Version of this interface. Currently 1.
     */
    standard_version: number;
}
export enum KeySource {
    /**
     * IC mainnet master keys.
     */
    Mainnet = "Mainnet",
    /**
     * PocketIC master keys, which local `icp network` also uses.
     */
    PocketIc = "PocketIc"
}
export interface sealed_secrets_canisterInterface {
    icp_sealed_secret_info(): Promise<Result>;
    icp_sealed_secret_list(): Promise<Result_1>;
    icp_sealed_secret_self_test(arg0: KeySource | null): Promise<Result_2>;
    icp_sealed_secret_set(arg0: string, arg1: Uint8Array): Promise<Result_3>;
    icp_sealed_secret_unset(arg0: string): Promise<Result_4>;
    secret_len(arg0: string): Promise<Result_3>;
    secret_reveal(arg0: string): Promise<Result_5>;
    secret_sha256(arg0: string): Promise<Result_6>;
}
import type { KeySource as _KeySource, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, SealedSecretEntry as _SealedSecretEntry, SealedSecretInfo as _SealedSecretInfo, SealedSecretsError as _SealedSecretsError, SelfTestReport as _SelfTestReport } from "./sealed_secrets_canister.did";
export class Sealed_secrets_canister implements sealed_secrets_canisterInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async icp_sealed_secret_info(): Promise<Result> {
        const result = await this.actor.icp_sealed_secret_info();
        return from_candid_Result_n1(result);
    }
    async icp_sealed_secret_list(): Promise<Result_1> {
        const result = await this.actor.icp_sealed_secret_list();
        return from_candid_Result_1_n5(result);
    }
    async icp_sealed_secret_self_test(arg0: KeySource | null): Promise<Result_2> {
        const result = await this.actor.icp_sealed_secret_self_test(to_candid_opt_n7(arg0));
        return from_candid_Result_2_n10(result);
    }
    async icp_sealed_secret_set(arg0: string, arg1: Uint8Array): Promise<Result_3> {
        const result = await this.actor.icp_sealed_secret_set(arg0, arg1);
        return from_candid_Result_3_n15(result);
    }
    async icp_sealed_secret_unset(arg0: string): Promise<Result_4> {
        const result = await this.actor.icp_sealed_secret_unset(arg0);
        return from_candid_Result_4_n17(result);
    }
    async secret_len(arg0: string): Promise<Result_3> {
        const result = await this.actor.secret_len(arg0);
        return from_candid_Result_3_n15(result);
    }
    async secret_reveal(arg0: string): Promise<Result_5> {
        const result = await this.actor.secret_reveal(arg0);
        return from_candid_Result_5_n19(result);
    }
    async secret_sha256(arg0: string): Promise<Result_6> {
        const result = await this.actor.secret_sha256(arg0);
        return from_candid_Result_6_n21(result);
    }
}
function from_candid_Result_1_n5(value: _Result_1): Result_1 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_2_n10(value: _Result_2): Result_2 {
    return from_candid_variant_n11(value);
}
function from_candid_Result_3_n15(value: _Result_3): Result_3 {
    return from_candid_variant_n16(value);
}
function from_candid_Result_4_n17(value: _Result_4): Result_4 {
    return from_candid_variant_n18(value);
}
function from_candid_Result_5_n19(value: _Result_5): Result_5 {
    return from_candid_variant_n20(value);
}
function from_candid_Result_6_n21(value: _Result_6): Result_6 {
    return from_candid_variant_n22(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_SealedSecretsError_n3(value: _SealedSecretsError): SealedSecretsError {
    return from_candid_variant_n4(value);
}
function from_candid_SelfTestReport_n12(value: _SelfTestReport): SelfTestReport {
    return from_candid_record_n13(value);
}
function from_candid_opt_n14(value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(value: {
    effective_context: Uint8Array;
    public_key_matches_master: [] | [boolean];
    epoch: number;
    effective_key_name: string;
    num_secrets: bigint;
    undecryptable: Array<string>;
    vetkd_derive_ok: boolean;
    vetkd_public_key_ok: boolean;
}): {
    effective_context: Uint8Array;
    public_key_matches_master?: boolean;
    epoch: number;
    effective_key_name: string;
    num_secrets: bigint;
    undecryptable: Array<string>;
    vetkd_derive_ok: boolean;
    vetkd_public_key_ok: boolean;
} {
    return {
        effective_context: value.effective_context,
        public_key_matches_master: record_opt_to_undefined(from_candid_opt_n14(value.public_key_matches_master)),
        epoch: value.epoch,
        effective_key_name: value.effective_key_name,
        num_secrets: value.num_secrets,
        undecryptable: value.undecryptable,
        vetkd_derive_ok: value.vetkd_derive_ok,
        vetkd_public_key_ok: value.vetkd_public_key_ok
    };
}
function from_candid_variant_n11(value: {
    Ok: _SelfTestReport;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: SelfTestReport;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_SelfTestReport_n12(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: bigint;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n18(value: {
    Ok: null;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _SealedSecretInfo;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: SealedSecretInfo;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: string;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n22(value: {
    Ok: Uint8Array;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: Uint8Array;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function from_candid_variant_n4(value: {
    Internal: string;
} | {
    TooMany: {
        max: bigint;
    };
} | {
    InvalidCiphertext: string;
} | {
    TooLarge: {
        max: bigint;
    };
} | {
    NotFound: null;
} | {
    Unauthorized: null;
} | {
    InvalidName: string;
} | {
    VetKdUnavailable: {
        detail: string;
        key_name: string;
    };
}): {
    __kind__: "Internal";
    Internal: string;
} | {
    __kind__: "TooMany";
    TooMany: {
        max: bigint;
    };
} | {
    __kind__: "InvalidCiphertext";
    InvalidCiphertext: string;
} | {
    __kind__: "TooLarge";
    TooLarge: {
        max: bigint;
    };
} | {
    __kind__: "NotFound";
    NotFound: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "InvalidName";
    InvalidName: string;
} | {
    __kind__: "VetKdUnavailable";
    VetKdUnavailable: {
        detail: string;
        key_name: string;
    };
} {
    return "Internal" in value ? {
        __kind__: "Internal",
        Internal: value.Internal
    } : "TooMany" in value ? {
        __kind__: "TooMany",
        TooMany: value.TooMany
    } : "InvalidCiphertext" in value ? {
        __kind__: "InvalidCiphertext",
        InvalidCiphertext: value.InvalidCiphertext
    } : "TooLarge" in value ? {
        __kind__: "TooLarge",
        TooLarge: value.TooLarge
    } : "NotFound" in value ? {
        __kind__: "NotFound",
        NotFound: value.NotFound
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "InvalidName" in value ? {
        __kind__: "InvalidName",
        InvalidName: value.InvalidName
    } : "VetKdUnavailable" in value ? {
        __kind__: "VetKdUnavailable",
        VetKdUnavailable: value.VetKdUnavailable
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: Array<_SealedSecretEntry>;
} | {
    Err: _SealedSecretsError;
}): {
    __kind__: "Ok";
    Ok: Array<SealedSecretEntry>;
} | {
    __kind__: "Err";
    Err: SealedSecretsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_SealedSecretsError_n3(value.Err)
    } : value;
}
function to_candid_KeySource_n8(value: KeySource): _KeySource {
    return to_candid_variant_n9(value);
}
function to_candid_opt_n7(value: KeySource | null): [] | [_KeySource] {
    return value === null ? candid_none() : candid_some(to_candid_KeySource_n8(value));
}
function to_candid_variant_n9(value: KeySource): {
    Mainnet: null;
} | {
    PocketIc: null;
} {
    return value == KeySource.Mainnet ? {
        Mainnet: null
    } : value == KeySource.PocketIc ? {
        PocketIc: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Sealed_secrets_canister {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Sealed_secrets_canister(actor);
}
